name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ join('Release v0.1.0 Last Alpha Commit ',github.sha) }}
          body: |
            We have made some features! A new step to being complete.
          draft: false
          prerelease: true
  buildm:
    name: Build on macOS
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir Debug && cd Debug
          g++ -MM -std=c++11 ../RichmanMA.cpp
          g++ -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"RichmanMA.d" -MT"RichmanMA.o" -o "RichmanMA.o" "../RichmanMA.cpp"
          g++  -o "RichmanMA" ./RichmanMA.o
      - name: upload asset
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./RichmanMA
          asset_name: Richman-For-macOS
          upload_url: ${{ steps.create_release.outputs.upload_url }}
  buildu:
    name: Build on ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir Debug && cd Debug
        g++ -MM -std=c++11 ../RichmanMA.cpp
        g++ -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"RichmanMA.d" -MT"RichmanMA.o" -o "RichmanMA.o" "../RichmanMA.cpp"
        g++  -o "RichmanMA" ./RichmanMA.o
    - name: upload asset
      id: upload-release-asset
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: ./RichmanMA
        asset_name: Richman-For-ubuntu
        upload_url: ${{ steps.create_release.outputs.upload_url }}
  buildw:
    name: Build on windows
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir Debug && cd Debug
          g++ -MM -std=c++11 ../RichmanMA.cpp
          g++ -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"RichmanMA.d" -MT"RichmanMA.o" -o "RichmanMA.o" "../RichmanMA.cpp"
          g++  -o "RichmanMA.exe" ./RichmanMA.o
      - name: upload asset
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: .\RichmanMA.exe
          asset_name: Richman-For-windows.exe
          upload_url: ${{ steps.create_release.outputs.upload_url }}
